[ios]

[ios:vars]
ansible_user=admin
ansible_password=cisco
ansible_network_os=ios
ansible_connection=network_cli
ansible_ssh_use_persistent_connections=false

[ios:children]
routers

[routers]
R1 ansible_host=10.255.1.60
R2 ansible_host=10.255.1.61
R3 ansible_host=10.255.1.62


